# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - lib/l10n/messages_*.dart

linter:
  rules:
    no_default_cases: false
    lines_longer_than_80_chars: false
