name: fluttersample
description: A new Flutter application.

version: 1.0.0+1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.9.0-21.10.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: any
  pedantic_mono: any

